config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :customers

  resources :waiters

  resources :table_nos

  resources :menus

  resources :categories

  get "/pay_amount", :to => 'orders#pay_amount'
  
  get "/reports", :to => 'reports#index'

  root :to =>'reports#index'

end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
	has_many :orders
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
  before_action :set_waiter, only: [:show, :edit, :update, :destroy]

  # GET /waiters
  # GET /waiters.json
  def index
    @waiters = Waiter.all
  end

  # GET /waiters/1
  # GET /waiters/1.json
  def show
  end

  # GET /waiters/new
  def new
    @waiter = Waiter.new
  end

  # GET /waiters/1/edit
  def edit
  end

  # POST /waiters
  # POST /waiters.json
  def create
    @waiter = Waiter.new(waiter_params)

    respond_to do |format|
      if @waiter.save
        format.html { redirect_to @waiter, notice: 'Waiter was successfully created.' }
        format.json { render :show, status: :created, location: @waiter }
      else
        format.html { render :new }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiters/1
  # PATCH/PUT /waiters/1.json
  def update
    respond_to do |format|
      if @waiter.update(waiter_params)
        format.html { redirect_to @waiter, notice: 'Waiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @waiter }
      else
        format.html { render :edit }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiters/1
  # DELETE /waiters/1.json
  def destroy
    @waiter.destroy
    respond_to do |format|
      format.html { redirect_to waiters_url, notice: 'Waiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiter
      @waiter = Waiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiter_params
      params.require(:waiter).permit(:name, :dob)
    end
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/waiters/_form.html.erb
<%= form_for(@waiter) do |f| %>
  <% if @waiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waiter.errors.count, "error") %> prohibited this waiter from being saved:</h2>

      <ul>
      <% @waiter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waiters/edit.html.erb
<h1>Editing Waiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @waiter %> |
<%= link_to 'Back', waiters_path %>

app/views/waiters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Waiters</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waiters.each do |waiter| %>
      <tr>
        <td><%= waiter.name %></td>
        <td><%= waiter.dob %></td>
        <td><%= link_to 'Show', waiter %></td>
        <td><%= link_to 'Edit', edit_waiter_path(waiter) %></td>
        <td><%= link_to 'Destroy', waiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waiter', new_waiter_path %>

app/views/waiters/new.html.erb
<h1>New Waiter</h1>

<%= render 'form' %>

<%= link_to 'Back', waiters_path %>

app/views/waiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @waiter.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @waiter.dob %>
</p>

<%= link_to 'Edit', edit_waiter_path(@waiter) %> |
<%= link_to 'Back', waiters_path %>