config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :customers

  resources :waiters

  resources :table_nos

  resources :menus

  resources :categories

  get "/pay_amount", :to => 'orders#pay_amount'
  
  get "/reports", :to => 'reports#index'

  root :to =>'reports#index'

end

app/models/table_no.rb
class TableNo < ActiveRecord::Base
	has_many :customers, :dependent => :destroy
	has_many :orders, :dependent => :destroy
end

app/controllers/table_nos_controller.rb
class TableNosController < ApplicationController
  before_action :set_table_no, only: [:show, :edit, :update, :destroy]

  # GET /table_nos
  # GET /table_nos.json
  def index
    @table_nos = TableNo.all
  end

  # GET /table_nos/1
  # GET /table_nos/1.json
  def show
  end

  # GET /table_nos/new
  def new
    @table_no = TableNo.new
  end

  # GET /table_nos/1/edit
  def edit
  end

  # POST /table_nos
  # POST /table_nos.json
  def create
    @table_no = TableNo.new(table_no_params)

    respond_to do |format|
      if @table_no.save
        format.html { redirect_to @table_no, notice: 'Table no was successfully created.' }
        format.json { render :show, status: :created, location: @table_no }
      else
        format.html { render :new }
        format.json { render json: @table_no.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_nos/1
  # PATCH/PUT /table_nos/1.json
  def update
    respond_to do |format|
      if @table_no.update(table_no_params)
        format.html { redirect_to @table_no, notice: 'Table no was successfully updated.' }
        format.json { render :show, status: :ok, location: @table_no }
      else
        format.html { render :edit }
        format.json { render json: @table_no.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_nos/1
  # DELETE /table_nos/1.json
  def destroy
    @table_no.destroy
    respond_to do |format|
      format.html { redirect_to table_nos_url, notice: 'Table no was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_no
      @table_no = TableNo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_no_params
      params.require(:table_no).permit(:name)
    end
end

app/helpers/table_nos_helper.rb
module TableNosHelper
end

app/views/table_nos/_form.html.erb
<%= form_for(@table_no) do |f| %>
  <% if @table_no.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table_no.errors.count, "error") %> prohibited this table_no from being saved:</h2>

      <ul>
      <% @table_no.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/table_nos/edit.html.erb
<h1>Editing Table No</h1>

<%= render 'form' %>

<%= link_to 'Show', @table_no %> |
<%= link_to 'Back', table_nos_path %>

app/views/table_nos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Table Nos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @table_nos.each do |table_no| %>
      <tr>
        <td><%= table_no.name %></td>
        <td><%= link_to 'Show', table_no %></td>
        <td><%= link_to 'Edit', edit_table_no_path(table_no) %></td>
        <td><%= link_to 'Destroy', table_no, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table no', new_table_no_path %>

app/views/table_nos/new.html.erb
<h1>New Table No</h1>

<%= render 'form' %>

<%= link_to 'Back', table_nos_path %>

app/views/table_nos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table_no.name %>
</p>

<%= link_to 'Edit', edit_table_no_path(@table_no) %> |
<%= link_to 'Back', table_nos_path %>